Add threaded-timer support to hpc-benchmark
INM-6/beNNch-models pull request #14
Opened 2024-12-17 14:26 UTC by JanVogelsang

Merge this as soon as https://github.com/nest/nest-simulator/pull/3378 is merged into NEST

2024-12-18 17:01 UTC, mlober requested changes
Thanks for this PR. Two things aside from my comments:
1) When benchmarking the logfiles contain e.g. a single value for time_update but also time_update_avg. What is the time_update timer here?

 2) All presim timers are given as tuples in the logfiles. The sim timers however are

2024-12-18 17:01 UTC, mlober commented on hpc_benchmark/hpc_benchmark.py
> +                d[timer] = timer_array[0]
What is the reason for adding only the first value of the tuple to the logfile? And why is this handled differently for the presim timers?

2025-02-11 12:39 UTC, JanVogelsang commented on hpc_benchmark/hpc_benchmark.py
> +    timers = ['time_collocate_spike_data', 'time_communicate_prepare', 'time_communicate_spike_data', 'time_communicate_target_data', 'time_construction_connect', 'time_construction_create', 'time_de
True!

2025-02-11 12:40 UTC, JanVogelsang commented on hpc_benchmark/hpc_benchmark.py
> +                d[timer + "_max"] = min(timer_array)
Thanks!

2025-02-11 13:26 UTC, mlober commented on hpc_benchmark/hpc_benchmark.py
> +                d[timer] = timer_array[0]
I see thanks. But why is this handled differently for sim time and presim time?

2025-02-11 15:44 UTC, JanVogelsang commented on hpc_benchmark/hpc_benchmark.py
> +                d[timer] = timer_array[0]
That was just an oversight from my side, I added the same code for presim as well now!

2025-02-11 15:46 UTC, mlober commented on hpc_benchmark/hpc_benchmark.py
> +                d[timer] = timer_array[0]
Thanks!

2025-02-11 15:54 UTC, closed without merging